commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - formservice-k8s/formservice-deployment.yml
  - formservice-k8s/formservice-service.yml
# service discovery eureka/consul

patchesJson6902:
