apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: formservice
      context: ../formservice
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
